MOTD: "Precipice Games MC Server!"

#canon stuff defined here
s: &survival
  port: 25565
  ip: 76.64.45.138

c: &creative
  port: 25565
  ip: 184.107.58.181

  
ff: &space
  port: 25565
  ip: 70.34.195.234

#lists of aliases
survival: *survival
mcsurvive: *survival
survive: *survival
mcsurvival: *survival
creative: *creative
mccreate: *creative
create: *creative
mccreative: *creative
finalfrontier: *space
space: *space
